gui:
  controls:
    previous-page:
      material: RED_STAINED_GLASS # Testing non-default
#      custom-model-data: 1 # This format is supported
    next-page:
      material: GREEN_STAINED_GLASS # Testing non-default
      custom-model-data: 2 # Testing
