name: Backpacks
version: '${project.version}'
main: io.github.ms5984.retrox.backpacks.internal.BackpacksPlugin
api-version: 1.19
authors: [ ms5984 ]
description: ${project.description}
depend: ["Accessories"]
libraries:
  - "io.github.ms5984.libraries:tag-lib:${project.tagLibVersion}"
  - "org.jetbrains.kotlin:kotlin-stdlib:${project.kotlinVersion}"
  - "cloud.commandframework:cloud-paper:${project.cloudVersion}"
  - "cloud.commandframework:cloud-annotations:${project.cloudVersion}"
